//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mebel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Accessories
    {
        public Accessories()
        {
            this.HardwareSpecification = new HashSet<HardwareSpecification>();
            this.SpecificationMaterials = new HashSet<SpecificationMaterials>();
        }
    
        public string Article { get; set; }
        public string Title { get; set; }
        public Nullable<int> UnitMeasurement { get; set; }
        public Nullable<int> Qty { get; set; }
        public Nullable<int> Supplier { get; set; }
        public string Image { get; set; }
        public Nullable<int> TypeHardware { get; set; }
        public Nullable<decimal> PurchasePrice { get; set; }
        public Nullable<int> Width { get; set; }
    
        public virtual Supplier Supplier1 { get; set; }
        public virtual TypeAccessories TypeAccessories { get; set; }
        public virtual UnitOfMeasurement UnitOfMeasurement { get; set; }
        public virtual ICollection<HardwareSpecification> HardwareSpecification { get; set; }
        public virtual ICollection<SpecificationMaterials> SpecificationMaterials { get; set; }
    }
}
