//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mebel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Equipment
    {
        public int Id { get; set; }
        public string Marking { get; set; }
        public Nullable<int> TypeOfEquipment { get; set; }
        public string Сharacteristics { get; set; }
    
        public virtual TypeEquipment TypeEquipment { get; set; }
    }
}
