//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mebel.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user24Entities : DbContext
    {
        public user24Entities()
            : base("name=user24Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Accessories> Accessories { get; set; }
        public DbSet<Equipment> Equipment { get; set; }
        public DbSet<HardwareSpecification> HardwareSpecification { get; set; }
        public DbSet<Material> Material { get; set; }
        public DbSet<OperationSpecification> OperationSpecification { get; set; }
        public DbSet<Order> Order { get; set; }
        public DbSet<Product> Product { get; set; }
        public DbSet<QualityMaterial> QualityMaterial { get; set; }
        public DbSet<Role> Role { get; set; }
        public DbSet<SpecificationAssemblyUnit> SpecificationAssemblyUnit { get; set; }
        public DbSet<SpecificationMaterials> SpecificationMaterials { get; set; }
        public DbSet<Status> Status { get; set; }
        public DbSet<Supplier> Supplier { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
        public DbSet<TypeAccessories> TypeAccessories { get; set; }
        public DbSet<TypeEquipment> TypeEquipment { get; set; }
        public DbSet<TypeOfMaterial> TypeOfMaterial { get; set; }
        public DbSet<UnitOfMeasurement> UnitOfMeasurement { get; set; }
        public DbSet<UnitOfMeasurementMaterial> UnitOfMeasurementMaterial { get; set; }
        public DbSet<User> User { get; set; }
    }
}
