//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mebel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationSpecification
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Operation { get; set; }
        public Nullable<int> SequenceNumber { get; set; }
        public Nullable<int> TypeEquipmentId { get; set; }
        public Nullable<System.TimeSpan> Time { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual TypeEquipment TypeEquipment { get; set; }
    }
}
