//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mebel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int Number { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string TitleOrder { get; set; }
        public Nullable<int> ProductId { get; set; }
        public Nullable<int> СustomerId { get; set; }
        public Nullable<int> ResponsibleManagerId { get; set; }
        public Nullable<decimal> Price { get; set; }
        public Nullable<System.DateTime> PlanDate { get; set; }
        public string Sceheme { get; set; }
        public Nullable<int> StatusId { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual Status Status { get; set; }
        public virtual User User { get; set; }
        public virtual User User1 { get; set; }
    }
}
