//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mebel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public Product()
        {
            this.HardwareSpecification = new HashSet<HardwareSpecification>();
            this.OperationSpecification = new HashSet<OperationSpecification>();
            this.ProductOrder = new HashSet<ProductOrder>();
            this.SpecificationAssemblyUnit = new HashSet<SpecificationAssemblyUnit>();
            this.SpecificationMaterials = new HashSet<SpecificationMaterials>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<HardwareSpecification> HardwareSpecification { get; set; }
        public virtual ICollection<OperationSpecification> OperationSpecification { get; set; }
        public virtual ICollection<ProductOrder> ProductOrder { get; set; }
        public virtual ICollection<SpecificationAssemblyUnit> SpecificationAssemblyUnit { get; set; }
        public virtual ICollection<SpecificationMaterials> SpecificationMaterials { get; set; }
    }
}
