//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mebel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationAssemblyUnit
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string AssemblyUnitPart { get; set; }
        public Nullable<int> Qty { get; set; }
    
        public virtual Product Product { get; set; }
    }
}
