//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mebel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpecificationMaterials
    {
        public int Id { get; set; }
        public int Product { get; set; }
        public string Material { get; set; }
        public int Qty { get; set; }
    
        public virtual Accessories Accessories { get; set; }
        public virtual Material Material1 { get; set; }
        public virtual Product Product1 { get; set; }
    }
}
