//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mebel.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class TypeEquipment
    {
        public TypeEquipment()
        {
            this.Equipment = new HashSet<Equipment>();
            this.OperationSpecification = new HashSet<OperationSpecification>();
        }
    
        public int Id { get; set; }
        public string Title { get; set; }
    
        public virtual ICollection<Equipment> Equipment { get; set; }
        public virtual ICollection<OperationSpecification> OperationSpecification { get; set; }
    }
}
